### PR TITLE
Create History.md

### PR DESCRIPTION
**Pull request by ccoenen**
I finally got around to adding this as a wiki page, originally discussed in https://github.com/input-leap/input-leap/discussions/1633

### CODE REVIEW

**Comment by shymega** [comment]
Thanks for this. I merged for speed, but maybe it's worth mentioning *why* Input Leap forked from Barrier. Do you mind if I edit that?

**Comment by ccoenen** [comment]
go ahead, I don't mind :-)

**Comment by karasuhebi** [comment]
Have you guys seen the history posted at deskflow? That's pretty good, too!

https://github.com/deskflow/deskflow/wiki/History

**Comment by shymega** [comment]
I have, yes.

**Pull request merged**
