### PR TITLE
Update Building-on-Linux.md

### PR DESCRIPTION
**Pull request by argoneus**
Add Wayland build instructions section

### CODE REVIEW

**Review by KoljaFrahm — COMMENTED** [review]
I can confirm this works

**Comment by KoljaFrahm** [comment]
libportal 0.8 is out on Fedora so it shouldn't need the part about installing libportal anymore

**Comment by KoljaFrahm** [comment]
IMO this is not needed anymore with https://github.com/input-leap/wiki-prs/pull/14 and can be closed

**Comment by shymega** [comment]
Agreed. Thank you @argoneus for your efforts - please do open PRs for the wiki if you find any other discrepancies.

**Pull request closed without merging**
